### ISSUE TITLE
INHERITANCE OOP CONCEPTS

### ISSUE THREAD

**Issue by vipulSharma18** [josharsh/Learning-Object-Oriented-Python#67]
**Is your feature request related to a problem? Please describe.**
I am adding inheritance in detail to the oop concepts

**Describe the solution you'd like**
code showing single, multiple inheritances and multi-level inheritance

**Comment by ajjayymahato** [comment]
Is this still open? Can I take up this issue?

**Comment by vipulSharma18** [comment]
Hey, it's been too long of a time for me to remember what happened here and why I was doing it. I can see the PR for this issue is merged already so this issue should be ideally closed. I'm closing it.
